{% set name = "zc.buildout" %}
{% set version = "2.13.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: {{ version }}
  git_url: https://github.com/buildout/buildout.git

build:
  number: 0
  entry_points:
    - buildout=zc.buildout.buildout:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools >=8.0
  run:
    - python
    - setuptools >=8.0

test:
  imports:
    - zc
    - zc.buildout
  commands:
    - buildout --help

about:
  home: "http://buildout.org"
  license: ZPL-2.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: "System for managing development buildouts"
  doc_url: http://www.buildout.org/en/latest/
  dev_url: https://github.com/buildout/buildout

extra:
  recipe-maintainers:
    - 183amir
    - lcolbois
